export const DIR = {
  PATH: '/path/to/root',
  SRC: 'src',
  DEST: 'dest',
  BUILD: 'build'
};

export const serve = {
  notify: false,
  startPath: D.PATH,
  ghostMode: false,
  server: {
    baseDir: './',
    index: `${D.DEST}${D.PATH}/`,
    routes: {
      [D.PATH]: `${D.DEST}${D.PATH}/`
    }
  }
};

export const scripts = {
  common: '',
  entryFiles: [
    `./${D.SRC}/js/main.js`//,
    // `./${D.SRC}/js/sub.coffee`
  ],
  browserifyOpts: {
    extensions: ['.coffee'],
    transform: ['babelify', 'coffeeify']
  },
  dest: `${D.DEST}${D.PATH}/js`
};

export const uglify = {
  src: `./${D.DEST}${D.PATH}/js/main.js`,
  dest: `${D.BUILD}${D.PATH}/js`,
  opts: {
    preserveComments(node, comment) {
      return comment.value.indexOf('* This header is generated by licensify (https://github.com/twada/licensify)') !== -1;
    }
  }
};

export const jade = {
  src: [
    `${D.SRC}/**/*.jade`,
    `!${D.SRC}/**/_**/*.jade`,
    `!${D.SRC}/**/_*.jade`
  ],
  dest: `${D.DEST}${D.PATH}`,
  opts: {
    pretty: false
  }
};

export const stylus = {
  src: [
    `${D.SRC}/**/*.styl`,
    `!${D.SRC}/**/_**/*.styl`,
    `!${D.SRC}/**/_*.styl`
  ],
  dest: `${D.DEST}${D.PATH}/css`
};

export const minifyCss = {
  src: `${D.DEST}${D.PATH}/css/main.css`,
  dest: `${D.BUILD}${D.PATH}/css`
};

export const imagemin = {
  src: [
    `${D.DEST}${D.PATH}/**/*.{jpg,jpeg,png,gif,svg}`
  ],
  dest: `${D.BUILD}${D.PATH}/img`
};

export const clean = {
  path: [`${D.BUILD}${D.PATH}`]
};

export const replace = {
  src: `${D.DEST}${D.PATH}/index.html`,
  dest: `${D.BUILD}${D.PATH}`,
  replacements: [
    ['main.js?v', `main.min.js?v=${Date.now()}`],
    ['main.css?v', `main.min.css?v=${Date.now()}`]
  ]
};

export const copy = {
  src: [
    `${D.DEST}/**`,
    `!${D.DEST}/css/**`,
    `!${D.DEST}/js/**`,
    `!${D.DEST}/img/**`
  ],
  dest: D.BUILD
};
